# Generated by Django 4.0.3 on 2022-04-19 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='thumbnail_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='thumbnail_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='thumbnail_images'),
        ),
    ]
