# Generated by Django 4.0.3 on 2022-04-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_presentation_thumbnail_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='thumbnail_image_url',
        ),
    ]
