# Generated by Django 4.0.3 on 2022-04-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
        ('main', '0004_remove_presentation_thumbnail_image_url'),
    ]

    operations = [
    ]
