# Generated by Django 4.0.3 on 2022-04-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='save_file'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_images'),
        ),
    ]
