# Generated by Django 4.0.3 on 2022-04-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_presentation_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
