# Generated by Django 4.0.3 on 2022-04-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_presentation_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='file_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
