# Generated by Django 4.0.3 on 2022-05-04 03:06

from django.db import migrations, models
import presentation.models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0012_presentation_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='presentation_id',
            field=models.CharField(default=presentation.models.generate_id, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
