# Generated by Django 4.0.3 on 2022-05-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0013_alter_presentation_presentation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presentation.category'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file',
            field=models.FileField(null=True, upload_to='save_file'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='thumbnail_image',
            field=models.ImageField(null=True, upload_to='thumbnail_images'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
